### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 0xh3LL0** [LazoCoder/Image-To-ASCII#2]
when i try to convert an image, it gave me error...
and since you didn't mention specific python & pil version i use python 3.4.2 and pillow 2.8.1
![error](https://user-images.githubusercontent.com/23132217/35259766-2e4fb9e0-003a-11e8-9b0a-c63816104c88.png)

**Comment by LazoVelko** [comment]
It looks like a font issue. I used Python 3.5 for this, not sure which version of pillow unfortunately. This was a toy program, there are much more sophisticated image to ascii projects out there. I recommend: https://github.com/IonicaBizau/image-to-ascii
